
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-7pm-4
owner: ucsb-cs156-w24
repo_name: team03-w24-7pm-4
pull_requests: [{"author":{"id":"U_kgDOBXzOLw","is_bot":false,"login":"wesley-hung","name":""},"headRefName":"whung-Articles-54","number":62,"title":"Created fixtures for Articles","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-4/pull/62"},{"author":{"id":"U_kgDOBXzOLw","is_bot":false,"login":"wesley-hung","name":""},"headRefName":"whung-Articles-53","number":61,"title":"Copied files for Backend CRUD API Articles from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-4/pull/61"}]
