
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-7pm-4
owner: ucsb-cs156-w24
repo_name: team03-w24-7pm-4
pull_requests: [{"author":{"id":"U_kgDOBXux7g","is_bot":false,"login":"wesleytruong","name":""},"headRefName":"wt-MenuItemReview-fix","number":98,"title":"fix typo in create page","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-4/pull/98"},{"author":{"id":"U_kgDOBdHhOA","is_bot":false,"login":"dhwang154","name":""},"headRefName":"dhwang154-recommendationRequest","number":97,"title":"Dhwang154 recommendation request","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-4/pull/97"}]
