
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-7pm-4
owner: ucsb-cs156-w24
repo_name: team03-w24-7pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQwNTQ2NDI3","is_bot":false,"login":"viditagrawal","name":""},"headRefName":"viditagrawal-team02migration","number":69,"title":"viditagrawal team03 finished code","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-4/pull/69"},{"author":{"id":"U_kgDOBXzOLw","is_bot":false,"login":"wesley-hung","name":""},"headRefName":"whung-Articles-57","number":68,"title":"Open Copy Placeholders for Articles pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-4/pull/68"},{"author":{"id":"U_kgDOBXux7g","is_bot":false,"login":"wesleytruong","name":""},"headRefName":"wt-MenuItemReview-fixtures","number":67,"title":"Wt menu item review fixtures","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-4/pull/67"},{"author":{"id":"U_kgDOBXux7g","is_bot":false,"login":"wesleytruong","name":""},"headRefName":"wt-MenuItemReview-team02","number":66,"title":"Copy files for Backend CRUD API MenuItemReview from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-4/pull/66"},{"author":{"id":"U_kgDOBXzOLw","is_bot":false,"login":"wesley-hung","name":""},"headRefName":"whung-Articles-56","number":65,"title":"Table Components for Articles plus tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-4/pull/65"},{"author":{"id":"U_kgDOBXzOLw","is_bot":false,"login":"wesley-hung","name":""},"headRefName":"whung-Articles-55","number":64,"title":"Formed Component for Articles plus tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-4/pull/64"},{"author":{"id":"U_kgDOBXzOLw","is_bot":false,"login":"wesley-hung","name":""},"headRefName":"whung-Articles-54","number":62,"title":"Created fixtures for Articles","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-4/pull/62"},{"author":{"id":"U_kgDOBXzOLw","is_bot":false,"login":"wesley-hung","name":""},"headRefName":"whung-Articles-53","number":61,"title":"Copied files for Backend CRUD API Articles from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-4/pull/61"}]
