
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-7pm-4
owner: ucsb-cs156-w24
repo_name: team03-w24-7pm-4
pull_requests: [{"author":{"id":"U_kgDOB3EM8A","is_bot":false,"login":"notaryaman","name":""},"headRefName":"as-editpagedcmenuitems","number":91,"title":"As editpagedcmenuitems","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-4/pull/91"},{"author":{"id":"U_kgDOB3EM8A","is_bot":false,"login":"notaryaman","name":""},"headRefName":"as-indexpagedcmenuitems","number":89,"title":"Index Page for UCSBDiningCommonsMenuItem plus tests and stories","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-4/pull/89"},{"author":{"id":"U_kgDOB3EM8A","is_bot":false,"login":"notaryaman","name":""},"headRefName":"as-createpagesmenuitems","number":88,"title":"Create Page for UCSBDiningCommonsMenuItem plus tests and stories","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-4/pull/88"},{"author":{"id":"U_kgDOBXzOLw","is_bot":false,"login":"wesley-hung","name":""},"headRefName":"whung-Articles-58","number":70,"title":"Create, Edit, and Index Pages for Articles","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-4/pull/70"},{"author":{"id":"U_kgDOBXzOLw","is_bot":false,"login":"wesley-hung","name":""},"headRefName":"whung-Articles-57","number":68,"title":"Open Copy Placeholders for Articles pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-4/pull/68"}]
